### ISSUE TITLE
How to use your library?

### ISSUE THREAD

**Issue by Alex-1357** [Dorin-Mocan/SignalRSwaggerGen#1]
Hello, Dorin. I have a question.
1. I add class to configureServices

            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo { Title = "Some API v1", Version = "v1" });
                // here some other configurations maybe...
                options.DocumentFilter<SignalRSwaggerGen.SignalRSwaggerGen>(new List<Assembly> { typeof(ChatHub).Assembly, typeof(ChatHub).Assembly });
            });

2. Add attributes to my chatHub

         [SignalRHub(path: "/chatHub")]

3. Add to app.UseEndpoints needed line

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<ChatHub>("/chatHub", options =>
                {
                    options.Transports =
                        HttpTransportType.WebSockets |
                        HttpTransportType.LongPolling;
                });
                endpoints.MapHub<ChatHub>(typeof(ChatHub).GetCustomAttribute<SignalRHubAttribute>().Path.Replace(Constants.HubNamePlaceholder, typeof(ChatHub).Name));
            });

4. Going to http://localhost:5000/swagger/v1/swagger.json (maybe this URL is wrong? I don't see right URL in your doc).

And receive nothing, I receive ordinary swagger spec of my controller inherited from ControllerBase.

What I done wrong?

**Comment by Dorin-Mocan** [comment]
Hi Alex,
You need to decorate the methods and their args with attributes as well.
--
Sent from Mail.ru app for Android Monday, 28 June 2021, 10:29PM +03:00 from Alex-1357  ***@***.*** :

**Comment by Dorin-Mocan** [comment]
Hi Alex,
First of all you don't need to map your hub twice. Do it just once. Second, when you pass the list of assemblies containing hubs, make sure to not have duplicate assemblies. Third is to decorate hub methods and their args with appropriate attributes. Please check the wiki page where I provided the documentation. If for some strange reason you fail to make it work, please contact me on Skype. My id is "dorin.mokan". Cheers!

**Comment by Alex-1357** [comment]
Thank you for fast answer. I have decorated, but no result. I still see only specification of controller inherits from ControllerBase
![Chat_06282021_224416](https://user-images.githubusercontent.com/86534217/123694858-87b34700-d862-11eb-8def-55c8f63b0c1d.png)

**Comment by Alex-1357** [comment]
Thank you, your program is working. Finally definition is

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<ChatHub>("/chatHub", options =>
                {
                    options.Transports =
                        HttpTransportType.WebSockets |
                        HttpTransportType.LongPolling;
                });

                //endpoints.MapHub<ChatHub>(typeof(ChatHub).GetCustomAttribute<SignalRHubAttribute>().Path.Replace(Constants.HubNamePlaceholder, typeof(ChatHub).Name));
            });

And, of course, attributes for method is needed. Thank you for fast answer.

**Comment by FiniteRealityTech** [comment]
I'm running into a similar issue but I'm not sure what I am doing wrong. I am not using any API controllers so I ended up adding the following line due to DI. I pasted my setup below as well.  I added the MapControllers() line to see if that would help this work or not.
             services.AddMvcCore()
                .AddApiExplorer();
                
Also, what is the address for the swagger gen because I try the same as Alex but without luck.
![image](https://user-images.githubusercontent.com/35709683/125086983-1bbeb300-e09a-11eb-9f15-2dc87ac77a24.png)
![image](https://user-images.githubusercontent.com/35709683/125087040-29743880-e09a-11eb-8459-feac7aec7829.png)
![image](https://user-images.githubusercontent.com/35709683/125087241-56c0e680-e09a-11eb-81ae-a05c8f5dc3d1.png)
![image](https://user-images.githubusercontent.com/35709683/125087299-62141200-e09a-11eb-8fad-8c8f8da33801.png)

**Comment by Dorin-Mocan** [comment]
@FiniteRealityTech ,
My SignalRSwaggerGen is dependent upon Swashbuckle.AspNetCore.SwaggerGen 6.1.4, so please make sure you're using the same version.

**Comment by Dorin-Mocan** [comment]
@FiniteRealityTech , most probably you forgot to enable Swagger doc whatsoever.  Please make sure that in Configure method of your web api application you do this:
```
app.UseSwagger();
app.UseSwaggerUI(options =>
{
	options.SwaggerEndpoint("/swagger/v1/swagger.json", "Your API V1");
	options.RoutePrefix = "your desired prefix";`
});
```

**Comment by FiniteRealityTech** [comment]
That's probably it, I have to make a small trip and then I'll try it. Thank you very much!

**Comment by FiniteRealityTech** [comment]
That was it exactly, thank you.
