### ISSUE TITLE
IEnumerables

### ISSUE THREAD

**Issue by RobertHaerle** [Dorin-Mocan/SignalRSwaggerGen#12]
Having a method with the signature
        [SignalRMethod(SignalR.Cartridges.ChangedSetupCartridgesEvent, OperationType.Get)]
        public async Task SendChangedSetupCartridgesAsync([SignalRArg("the info about the changes.", typeof (CartridgeInfoSignalR[]))] CartridgeInfoSignalR[] changedSetupCartridges)
        generates only an object array in swagger.html

changedSetupCartridges | the info about the changes.
array[object]
(query) 
 
"Try It Out" somehow finds the class used as an argument

**Comment by Dorin-Mocan** [comment]
Hello @RobertHaerle , I'll investigate the issues by tomorrow evening and come back to you. Sorry for not reacting quicker, it's just I haven't entered GitHub for several days.

**Comment by Dorin-Mocan** [comment]
@RobertHaerle , unfortunately Swagger does not support parameters of complex type array, only arrays of primitive type. For reference: https://swagger.io/docs/specification/2-0/describing-parameters/#array
On the bottom of the page in FAQ section the following is mentioned:
schema is only used with in: body parameters. Any other parameters expect a primitive type, such as type: string, or an array of primitives.
