### ISSUE TITLE
Structural Error in Swagger Editor

### ISSUE THREAD

**Issue by ruzgarustu** [Dorin-Mocan/SignalRSwaggerGen#13]
First, thank you for the library. 
Recently I noticed that I get "structural errors" in Swagger editor (https://editor.swagger.io/) for the hub methods that I annotated with SignalRMethodAttribute only, like: 

![image](https://user-images.githubusercontent.com/18558510/148944820-00c764ce-97c5-468e-b49f-052b99756756.png)

I can oversimplify the method like this just to demonstrate:

```
[SignalRMethod(name: "AwaitMeetingEvents", summary: "Await Meeting Events")]
        public async Task AwaitMeetingEvents(IHubContext<EventHub> hubContext)
        {
              await hubContext.Clients.User(userGuid.Value).SendAsync(eventName, arg);
         }
```
So no return value and no explicit response as in an http endpoint, which totally makes sense. But could there still be a way to get rid of this structural error in Swagger editor? A boilerplate annotation or something I could have missed?

**Comment by Dorin-Mocan** [comment]
@ruzgarustu , hello pal. I'll investigate the issues today or tomorrow in the evening and come back to you asap. Thank you for understanding!

**Comment by Dorin-Mocan** [comment]
@ruzgarustu , I think you are using incorrectly the package(at least from what I see in the oversimplified example). You need to decorate only the methods that have the same signature as the methods you want to invoke on the frontend let's say. So if on frontend you have a method called "TestMethod" and it takes the parameters: number a, string b, boolean c, then you need in your hub to add a method with same name and same parameters and decorate it with the appropriate attributes. In the example of yours you have as method parameter a hub context. \do you really intend to pass to the frontend the hub context object?))
