### ISSUE TITLE
Generate documentation for hub in a sub-assembly

### ISSUE THREAD

**Issue by jaytonic** [Dorin-Mocan/SignalRSwaggerGen#17]
Hi,

I've my Asp.Net core splited in several projects. I do reference them in my main Program.cs like this:

```
[...]
builder.Services.AddControllers()
    .PartManager.ApplicationParts.Add(new AssemblyPart(typeof(SomeClassOfMyOtherAssembly).Assembly));

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
	options.SwaggerDoc("v1", new OpenApiInfo(){Title = "Wonderfull API"});
	options.AddSignalRSwaggerGen();
});
[...]
```

All my controllers are currently in those  other assemblies, and when I display swagger, those other controller are properly displayed.

In this other project, I've a Strongly typed Hub:
 ```
   [SignalRHub]

    public class ProjectHub:Hub<IProjectHubClient>
    {
    }
    public interface IProjectHubClient
    {
        Task DashboardDeleted(Guid dashboardId);

        Task DashboardInserted(DashboardDto dashboardDto);

        Task DashboardUpdated(DashboardDto dashboardDto);
    }
```

But when I build and launch the project, there is nothing on the swagger web page that display my web socket. Am I missing something or is this just not supported?

**Comment by Dorin-Mocan** [comment]
@jaytonic , you can pass to AddSignalRSwaggerGen() method the assemblies that need to be scanned. Please try, and if you can't figure out how, let me know, I'll help.
