### ISSUE TITLE
Inconsistency in Type parameter in Attributes

### ISSUE THREAD

**Issue by RobertHaerle** [Dorin-Mocan/SignalRSwaggerGen#19]
The ```SignalRRequestBody``` is able to display typeof(ComplexType[]) in the swagger UI.
But if the Type in the attribute ```SignalRParam``` is set to an array or an IEnumerable just nothing shows up in the swagger UI. It only works with a single complex type. 
I'd suggest that the attributes behave similar.
Thank you

**Comment by Dorin-Mocan** [comment]
@RobertHaerle , unfortunately Swagger does not support complex type array as parameters, only arrays of primitive type. For reference: [swagger documentation](https://swagger.io/docs/specification/2-0/describing-parameters/#array)
On the bottom of the page in FAQ section the following is mentioned:
schema is only used with in: body parameters. Any other parameters expect a primitive type, such as type: string, or an array of primitives.

You can observe the same issue if you try adding complex type arrays as query parameters for controller actions.

**Comment by RobertHaerle** [comment]
you're right, sorry. Wouldn't it be a idea to fool swagger into believing a parameter could be a body parameter eg. by extending the SignalRParam ctor by a enum that allows to select sth like TreatAsFromBody?
I know this is difficult as you try to describe an event like a function. Thanks anyway for your really impressing functionality.

**Comment by RobertHaerle** [comment]
Thank you very much for your work!
