### ISSUE TITLE
Signal R Testing

### ISSUE THREAD

**Issue by FiniteRealityTech** [Dorin-Mocan/SignalRSwaggerGen#2]
I was wondering if it was even possible to make it so you can test hub methods the same way you can test api endpoints. For the most part, I usually develop my own interface to do it, but building it into Swagger would be a huge time saver.

**Comment by Dorin-Mocan** [comment]
Unfortunately I don't see how I could add support for your request right now, though I might do an investigation.

**Comment by FiniteRealityTech** [comment]
I make interfaces for my projects currently with Vue. I'm curious if there's a way to just take the Swagger data and slap that into its own Vue or similar type of frontend. Then, when the project is ran, it would basically create a website, launch the site and start itself. There's just a complete lack of this ability and makes testing and development difficult. I may take some time to look into solutions as well.

**Comment by Dorin-Mocan** [comment]
@FiniteRealityTech , sorry for delayed response. What you could do, is try to write a js script which connects to the desired hub, and when some methods on the client side get invoked, somehow manipulate the html on the page. You can inject this js in the swagger document like this: app.UseSwaggerUI(options => options.InjectJavascript("path to js", "text/javascript"));
