### ISSUE TITLE
.Net Standard 2.0 Support

### ISSUE THREAD

**Issue by CoenraadS** [Dorin-Mocan/SignalRSwaggerGen#20]
Hi great package!

I was wondering if perhaps it would be possible multi-target this project to build both .Net standard 2.1 and 2.0 nuget packages.

For us poor souls stuck on Framework 🐮

**Comment by Dorin-Mocan** [comment]
@CoenraadS , hi! I'll try build a version for 2.0. Stay tuned.

**Comment by CoenraadS** [comment]
I'm not sure if it matters, but since there are so many different packages, I'm using

`<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />`

Despite it's name, this package also works on framework. On our project we basically upgraded as far as we could, before packages became core exclusive. This means we are also using:

```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="3.2.0" />
    ```
    
    If required I can upload a demo project.

**Comment by Dorin-Mocan** [comment]
@CoenraadS , I published a preview version of my package. Please test if it works with your project and let me know. Thanks!

**Comment by CoenraadS** [comment]
It's working <3

**Comment by Dorin-Mocan** [comment]
@CoenraadS , you can add xml comments and set the http verb like this:
 `options.AddSignalRSwaggerGen(x =>
{
	x.UseXmlComments("path to xml comments file");
	x.Operation = Operation.Get;
});`
If I can help with anything else, let me know.
