### ISSUE TITLE
Add support for authorization

### ISSUE THREAD

**Issue by frederikstonge** [Dorin-Mocan/SignalRSwaggerGen#21]
Using the authorize attribute doesn't show up as a protected endpoint.

**Comment by Dorin-Mocan** [comment]
@frederikstonge , I'll add support for this in short time.

**Comment by Dorin-Mocan** [comment]
@frederikstonge , version 3.2.0-preview.2 has been released. Please let me know it it covers your need.

**Comment by frederikstonge** [comment]
Wow thanks, trying in a few minutes

**Comment by frederikstonge** [comment]
It works! Thanks!
