### ISSUE TITLE
Whitespaces after method name and before query parameters

### ISSUE THREAD

**Issue by imabusyman** [Dorin-Mocan/SignalRSwaggerGen#23]
https://localhost:44392/hubs/StronglyTypedTestHub/TestMethod    ?agr1=1&arg2=1&date=2022-05-05T12%3A26%3A33.378Z&temperatureC=0&summary=string

This is causing error 

<html>
<body>

404Undocumented | Error: response status is 404Response headers date: Thu,05 May 2022 12:32:03 GMT  request-context: appId=cid-v1:fa498c63-faea-4730-9f8f-9b6a12fb489a  server: Microsoft-IIS/10.0  x-powered-by: ASP.NET
-- | --

</body>
</html>

**Comment by imabusyman** [comment]
This happens on code

        private string GetMethodPath(string hubPath, MethodInfo method, SignalRHubAttribute hubAttribute, SignalRMethodAttribute methodAttribute)
        {
            var methodPathSuffix = new string(' ', method.GetParameters().Length)**; <----HERE**
            var methodName = methodAttribute == null
                ? method.Name
                : methodAttribute.Name.Replace(Constants.MethodNamePlaceholder, method.Name);
            var nameTransformer = hubAttribute.NameTransformer ?? _options.NameTransformer;
            if (nameTransformer != null) methodName = nameTransformer.Transform(methodName);
            return $"{hubPath}/{methodName}{methodPathSuffix}";
        }

**Comment by Dorin-Mocan** [comment]
@imabusyman , please close the issue if it is not relevant to you anymore. Thanks!
