### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by fredrikbergholtz-sr** [Dorin-Mocan/SignalRSwaggerGen#24]
Is it possible to specify custom tags to SignalR methods in order to modify groupings in the UI?

Regular HTTP swagger can do this via the use of Swashbuckle.AspNetCore.Annotations:

[SwaggerOperation(Tags = new[] { "MyTag" })]
Task MyMethod() {...}

After c.EnableAnnotations() is called in the AddSwaggerGen configuration method.

I can't see anything in the code for the SignalRMethod attribute where I would expect to find it. It also doesn't help to specify a SwaggerOperation attribute to my SignalR method.

**Comment by Dorin-Mocan** [comment]
@fredrikbergholtz-sr , hello! Currently there's no possibility to specify separate tag(s) for methods. I will add this feature asap. It might happen today, but I don't guarantee it, but by the end of this week I'll release this feature for sure, so stay tuned.

**Comment by fredrikbergholtz-sr** [comment]
@Dorin-Mocan That is awesome! I was just about to fork and try to add it myself. :-)

At this time, a single tag fed in through the SignalRMethod attribute would suffice for the project I am currently working on.

**Comment by Dorin-Mocan** [comment]
@fredrikbergholtz-sr , I just released a new version 3.3.0. Check out. If you like the package, please hit toss a star for this repo. Thanks!

**Comment by fredrikbergholtz-sr** [comment]
It works! Thanks for the impressively quick fix!
