### ISSUE TITLE
Is it possible to display <examples> and <remarks> from XML documentation?

### ISSUE THREAD

**Issue by kristian-regec** [Dorin-Mocan/SignalRSwaggerGen#26]
I have controller and SignalR hub in the same project. For controller **example** and **remarks** from XML documentation are included in swagger documentation but not for SignalR hub class. Is it possible to enable this somehow?
Sample controller method:

![image](https://user-images.githubusercontent.com/94677977/188491074-89cc56bb-adcb-4f73-9126-611fd04020cd.png)

Thank you.

**Comment by Dorin-Mocan** [comment]
@kristian-regec , investigating. Will come back to you asap, so stay tuned.

**Comment by Dorin-Mocan** [comment]
@kristian-regec , hi! I just released the version 3.4.0 which has support for <remakrs> in XML comments. As for <example>, I could not make it to appear in Swagger after I added this tag for controller actions. Could you please elaborate more on how you're intending to use this tag? Thanks!
