### ISSUE TITLE
Receive Socket response in swagger

### ISSUE THREAD

**Issue by geghamhunanyan** [Dorin-Mocan/SignalRSwaggerGen#28]
How can I receive socket response message in swagger or postman?

**Comment by Dorin-Mocan** [comment]
@geghamhunanyan , hi! For the moment it is not possible to receive and send messages through websockets from swagger. My package only makes it possible to display signalr hubs, but not interact with them. You need to raise this topic to swagger team. Thanks for understanding and for using my package. Please toss a star if you want to help me. Thanks again !
