### ISSUE TITLE
Depend on a non-buggy version of Swashbuckle.AspNetCore.SwaggerGen

### ISSUE THREAD

**Issue by oyzar** [Dorin-Mocan/SignalRSwaggerGen#29]
Swashbuckle.AspNetCore.SwaggerGen has a bug in version 6.3.0 and higher that makes it difficult to use https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2368 . But this project isn't compatible with 6.2.3 due to the constraint. Can you please change the constraint so it will work with 6.2.3?

**Comment by Dorin-Mocan** [comment]
@oyzar , sorry for delayed response, I'll try put a lower version as a dependency. Will notify you when I release a new version. Thanks for raising this issue. Please toss a star for this repo in order to support my work. Thanks again!

**Comment by Dorin-Mocan** [comment]
@oyzar , I just released the version 3.7.0 which depends on Swashbuckle.AspNetCore.SwaggerGen version 6.0.0. Please toss a star for this repo on GitHub in order to support my work. Thank you!
