### ISSUE TITLE
Method Deprecation

### ISSUE THREAD

**Issue by orionstudt** [Dorin-Mocan/SignalRSwaggerGen#30]
Please check for `ObsoleteAttribute` on the hub `MethodInfo` in order to set `operation.Deprecated = true` on the swagger operation. Better yet, allow us to hook into your `IDocumentFilter` implementation with some mechanism similar to `IOperationFilter` so that we can add our own customizations once your implementation has created the operation.

**Comment by Dorin-Mocan** [comment]
@orionstudt , will investigate your issue asap and come back with a reply. Thank you for contribution!

**Comment by Dorin-Mocan** [comment]
@orionstudt , I have added support for Obsolete attribute, will release a new version soon. As for the hook, I'm working on it.

**Comment by Dorin-Mocan** [comment]
@orionstudt , just released the version 3.8.0 with support for deprecation. Please toss a star for this repo on GitHub in order to support my work. Thank you!

**Comment by orionstudt** [comment]
Thanks for the effort!

**Comment by Dorin-Mocan** [comment]
@orionstudt , I just released a major version 4.0.0 which has support for filters. Thanks for contribution. Happy new year!

**Comment by orionstudt** [comment]
@Dorin-Mocan Just checked it out, that's awesome, thank you so much!
