### ISSUE TITLE
SignalRHubAttribute not working with Moq

### ISSUE THREAD

**Issue by VitaliiShevchuk99** [Dorin-Mocan/SignalRSwaggerGen#32]
Mock.Object is null when I add SignalRHubAttribute to the mocked interface. It works well with other's attributes
Moq Version 4.18.1
SignalRSwaggerGen Version 4.1.0

**Comment by Dorin-Mocan** [comment]
@VitaliiShevchuk99 hi! Could you please elaborate more? Maybe you could show a code snippet?

**Comment by VitaliiShevchuk99** [comment]
Interface: 
```
[SignalRHub]
public interface ITestHub
{
    Task RemoveTest(long e);
}

```
Hub:

```
public class TestHub: Hub<ITestHub>
{
    public async Task SomeMethod(long arg1)
    {
        await Clients.All.RemoveTest(arg1);
    }
}

```
Test: 
```
    internal class TestSignalR
    {

        private readonly Mock<ITestHub> _hubMock;

        public TestSignalR()
        {

            _hubMock = new Mock<ITestHub>(MockBehavior.Strict);
            var object1 = _hubMock.Object;
        }

        [Test]
        public void TestHub()
        {
            var test = 0;
        }
    }
```
    
Result with attribute:

![image](https://user-images.githubusercontent.com/37291043/217806147-0029a3b4-4658-466a-9641-680d0b2b85d9.png)

Result without attribute:
![image](https://user-images.githubusercontent.com/37291043/217806816-81184f48-6e30-45db-9afa-3b7bbbd59c21.png)

**Comment by Dorin-Mocan** [comment]
@VitaliiShevchuk99 , it's a problem of Moq. I updated Moq to version 4.18.4 and everything works.
