### ISSUE TITLE
SignalRRequestBody attribute disappeared. 

### ISSUE THREAD

**Issue by KlestovAlexej** [Dorin-Mocan/SignalRSwaggerGen#33]
SignalRRequestBody attribute disappeared. 
Now Swagger UI  has no request schemas.

**Comment by Dorin-Mocan** [comment]
@KlestovAlexej , yes, in the new versions of SignalRSwaggerGen in order to specify that a parameter is mapped to the request body, you need to decorate the paratemer with [FromBody], [FromForm].

**Comment by KlestovAlexej** [comment]
Thank you! Works.

**Comment by Dorin-Mocan** [comment]
@KlestovAlexej , please toss a start for this repo in order to support my work. Thanks!
