### ISSUE TITLE
Show summary information for SignalRHub

### ISSUE THREAD

**Issue by arisliang** [Dorin-Mocan/SignalRSwaggerGen#35]
Is there a summary option for documenting the hub `[SignalRHub]`? It doesn't seem to pick up from summary as usually swagger does. Also `[SignalRMethod]` has a summary option for swagger display, can SignalRHub specify summary as well?

**Comment by Dorin-Mocan** [comment]
@arisliang , I did not know that it's possible to specify a summary for a controller. As far as I know it's only possible to have summary for the endpoints. Could you please show me how it should look like on UI?

**Comment by arisliang** [comment]
Basically just summary information at the hub level, which we have at the method level.

![image](https://user-images.githubusercontent.com/1115503/220312192-781a8055-ffab-4b37-90ee-2543375aa265.png)

**Comment by Dorin-Mocan** [comment]
@arisliang   I'll investigate.

**Comment by Dorin-Mocan** [comment]
@arisliang , I'll add support for specifying description for hubs in next release, which will happen soon. Stay tuned.

**Comment by Dorin-Mocan** [comment]
@arisliang I just released the version 4.2.0, which has support for specifying hub description via hub attribute or via xml comments. Thank you for contribution.

**Comment by arisliang** [comment]
Tried new version and works, thanks!
