### ISSUE TITLE
Events typed via client interface show up in Swagger but do not contain any type information

### ISSUE THREAD

**Issue by TheRealAyCe** [Dorin-Mocan/SignalRSwaggerGen#36]
This hub
```csharp
public interface INiceHubClient
{
    Task StateUpdate(UpdateDto updateData);
}

public class NiceHub : Hub<INiceHubClient>
{
}
```
should show up as having 1 event. The event shows, but the type specification for UpdateDto is not available, nor is the info that the event has it as its first and only parameter. It acts like it's just a void function and calling it obviously fails.

**Comment by Dorin-Mocan** [comment]
@TheRealAyCe I don't see your interface to be decorated with SignalRHub attribute. Could you please share the full code? Also include UpdateDto class so that I can see why it doesn't show up. Thank you!

**Comment by TheRealAyCe** [comment]
![clienthubonly](https://user-images.githubusercontent.com/11407231/225022822-f0b62ccb-14f8-4c3a-a51f-868538c54ca9.png)
I expect client events and server methods to be listed under the same "controller", as they are all related to the same hub.

I can see the type definition now, but the "POST" methods don't work. Probably does not make sense to allow these calls if it just tries to call HTTP and doesn't actually work?
```csharp

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.OpenApi.Models;
using SignalRSwaggerGen.Attributes;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddSignalR();
builder.Services.AddControllers();

builder.Services.AddSwaggerGen(c =>
{
    //Locate the XML file being generated by ASP.NET...
    var xmlFile = Assembly.GetExecutingAssembly().GetName().Name + ".xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

    //... and tell Swagger to use those XML comments.
    c.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "API", Version = "v1" });
    c.AddSignalRSwaggerGen();
});

var app = builder.Build();

app.UseDeveloperExceptionPage();
app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();
app.MapHub<NiceHub>("/niceHub");

app.Run();

[Route("api/[controller]")]
[ApiController]
public class NiceController : ControllerBase
{
    /// <summary>
    /// Get some nice data.
    /// </summary>
    [HttpGet]
    public NiceData Get()
    {
        return new("nice!");
    }
}

public record NiceData(string What);

[SignalRHub]
public interface INiceHubClient
{
    Task StateUpdate(UpdateDto updateData);
}

[SignalRHub]
public class NiceHub : Hub<INiceHubClient>
{
    public async Task DoNothing(string name)
    {
        await Task.Delay(1000);
    }
}

public record UpdateDto(string NewName, string NewValue);

```

**Comment by Dorin-Mocan** [comment]
@TheRealAyCe SignalRSwaggerGen does not allow interaction with the server, it only allows displaying hubs(for documentation purpose). If you want both methods under same tag, you could rename the interface to INiceHub or use a parameter in SignalRHub attribute to specify the tag name. Please toss a start to this repo in order to support my work. Thank you!
