### ISSUE TITLE
Move Attributes into SignalRSwaggerGen.Core package

### ISSUE THREAD

**Issue by Floyddotnet** [Dorin-Mocan/SignalRSwaggerGen#37]
I recommend to move all Attributes into a new SignalRSwaggerGen.Core package.

I have interface projects for .net SignalR clients and i'm not happy to add the whole OpenApi and Sawshbuckle stuff to this too.

```
Project: myProject.SignalRClientInterface
Install SignalRSwaggerGen.4.2.0

Requires:

Microsoft.OpenApi.1.2.3
Swashbuckle.AspNetCore.Swagger.6.0.0
Swashbuckle.AspNetCore.SwaggerGen.6.0.0
```

I mean somthing like `Microsoft.AspNetCore.Mvc.Core` with provies only ASP.NET Core MVC core components. Contains common action result types, attribute routing, application model conventions, API explorer, application parts, filters, formatters, model binding, and more.

**Comment by Dorin-Mocan** [comment]
@Floyddotnet , I think it's a good idea to have a Core package. Will work on it in the following days, so stay tuned. Thanks for contribution.

**Comment by Dorin-Mocan** [comment]
@Floyddotnet I'm about to release the Core package. Don't lose hope :D

**Comment by Dorin-Mocan** [comment]
@Floyddotnet I just released SignalRSwaggerGen.4.4.0 and SignalRSwaggerGen.Core.1.0.0.

**Comment by Floyddotnet** [comment]
> @Floyddotnet I just released SignalRSwaggerGen.4.4.0 and SignalRSwaggerGen.Core.1.0.0.

thank you very mutch
