### ISSUE TITLE
Bug: Arrays are not serialized in method parameters correctly

### ISSUE THREAD

**Issue by Floyddotnet** [Dorin-Mocan/SignalRSwaggerGen#38]
sample:

```
[SignalRHub]
public interface SampleHub{
  Task SampleMethod(MyObject[] model);
}
```

is rendered in Swagger-UI as 

```
model
array[object]
(query)
```

![image](https://user-images.githubusercontent.com/498914/228973841-332916a4-1efc-42e1-926e-86f54755cb30.png)

**Comment by Dorin-Mocan** [comment]
@Floyddotnet just decorate the parameter with FromBodyAttribute.

**Comment by Floyddotnet** [comment]
> @Floyddotnet just decorate the parameter with FromBodyAttribute.

ok thx, i will try this
