### ISSUE TITLE
Can't use [SignalRHub] in inheritted interface 

### ISSUE THREAD

**Issue by quannv108** [Dorin-Mocan/SignalRSwaggerGen#39]
example:
```CSharp
public interface IMainHubServerToClient
{
    Task HiAsync();
}

[SignalRHub]
public interface IMainHubClient : IMainHubServerToClient
{
    
}
```

The Swagger will show nothing.

**Comment by Dorin-Mocan** [comment]
@quannv108 hi, yes, inherited members are not scanned. This is done deliberately in case a hub inherits from a class/interface with members that should not be seen in Swagger. The solution is simple:

        [SignalRHub(tag: "some-tag", path: "/some/path")]
	public interface IMainHubServerToClient
	{
		Task HiAsync();
	}

	[SignalRHub(tag: "some-tag", path: "/some/path")]
	public interface IMainHubClient : IMainHubServerToClient
	{
		Task ByeAsync();
	}
