### ISSUE TITLE
Security not working

### ISSUE THREAD

**Issue by PeterKottas** [Dorin-Mocan/SignalRSwaggerGen#41]
Hi, I am on v4.4, just testing this out. I am not seeing any security metadata and the authorizations UI is also missing in the Swashbuckle UI. This is my hub:
```
[Authorize]
[SignalRHub(path: "hubs/main")]
public class SignalRMainCore : Hub, ISignalRMain {}
```
Method:
```
[SignalRMethod("JoinChat")]
public async Task JoinChat(long chatId, RoleTypeEnum roleType)
```

And setup code:
```
c.AddSignalRSwaggerGen(options =>
                {
                    options.UseHubXmlCommentsSummaryAsTagDescription = true;
                    options.UseHubXmlCommentsSummaryAsTag = true;
                    options.UseXmlComments(signalXmlCommentsPath);
                    options.ScanAssemblies(
                        AppDomain.CurrentDomain
                            .GetAssemblies()
                            .Where(a => a.FullName.StartsWith("GuestBell"))
                    );
                });
```

The rest of the setup is quite complex, but nothing that would override any default behavior. E.g. whenever we add to the definition, we add not overwrite. Based on https://github.com/essencebit/SignalRSwaggerGen/issues/21, this should be working. I assume it should work if I add the definition manually using the AddSecurityRequirement on the options object. But I think this should work automatically.  Is there anything I missed? Thanks!

**Comment by Dorin-Mocan** [comment]
Hi @PeterKottas , you need to AddSecurityDefinition and AddSecurityRequirement for SwaggerGenOptions.

**Comment by PeterKottas** [comment]
Thanks @Dorin-Mocan yep we have the definition added in Swagger options. I think the requirements could be added automatically. Maybe it can be a "feature". Here is the code we use to add some definitions from reflection via IOperationFilter. I think this could be supported out of the box.

```
public class AuthorizeGuestAuthTokenCheckOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var found = false;
            if (
                context.ApiDescription.ActionDescriptor
                is Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor controller
            )
            {
                found = controller.ControllerTypeInfo
                    .GetCustomAttributes()
                    .OfType<AllowGuestAuthTokenAttribute>()
                    .Any();
            }
            if (!found)
            {
                if (!context.ApiDescription.TryGetMethodInfo(out var mi))
                    return;
                if (!mi.GetCustomAttributes().OfType<AllowGuestAuthTokenAttribute>().Any())
                    return;
            }

            if (!operation.Responses.ContainsKey("401"))
            {
                operation.Responses.Add(
                    "401",
                    new OpenApiResponse { Description = "Unauthorized" }
                );
            }
            if (!operation.Responses.ContainsKey("403"))
            {
                operation.Responses.Add("403", new OpenApiResponse { Description = "Forbidden" });
            }

            var guestAuthTokenScheme = new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = GuestAuthTokenAuthenticationOptions.AuthenticationScheme
                }
            };

            if (operation.Security == null)
            {
                operation.Security = new List<OpenApiSecurityRequirement>();
            }
            operation.Security = operation.Security
                .Concat(
                    new List<OpenApiSecurityRequirement>
                    {
                        new OpenApiSecurityRequirement
                        {
                            [guestAuthTokenScheme] = new List<string>() { "GuestBell.Host.Backend" }
                        }
                    }
                )
                .ToList();
        }
    }
```
You could just rename a bit, use your attributes and provide the default definition via options in AddSignalRSwaggerGen. 
I hope this is helpful, happy to give you a hand if you consider this worth adding. I think it's what users would expect.

**Comment by Dorin-Mocan** [comment]
@PeterKottas if you already have defined the security scheme and requirement and added them to SwaggerOptions, they should be applied for the hubs as well, they are inherited, no need to specify them explicitly for SignalRSwaggerGenOptions.

**Comment by PeterKottas** [comment]
Ok, so this is something that is not working for me then. We use a combination of the previously posted OperationFilter and add the security definition as follows:
```
c.AddSecurityDefinition(
                    "oauth2",
                    new OpenApiSecurityScheme
                    {
                        Type = SecuritySchemeType.OAuth2,
                        Flows = new OpenApiOAuthFlows
                        {
                            Implicit = new OpenApiOAuthFlow
                            {
                                AuthorizationUrl = new Uri(
                                    Configuration["Auth:Url"] + "connect/authorize"
                                ),
                                // TokenUrl = new Uri(Configuration["Auth:Url"] + "connect/token"),
                                Scopes = new Dictionary<string, string>
                                {
                                    { "GuestBell.Host.Backend", "GuestBell Backend" }
                                },
                            }
                        }
                    }
                );
```

I'd say the setup is pretty standard. Not sure why it's not being picked up for the signalR as well.

**Comment by Dorin-Mocan** [comment]
@PeterKottas I'll check your example in the following days and come back to you. Stay tuned.

**Comment by PeterKottas** [comment]
Cheers!

**Comment by Dorin-Mocan** [comment]
@PeterKottas you need to add the security requirement on SwaggerGenOptions or on SignalRSwaggerGenOptions and it'll be applied to hub endpoints in Swagger doc.

`o.AddSecurityRequirement(new OpenApiSecurityRequirement
					{
						{
						new OpenApiSecurityScheme
						{
							Reference = new OpenApiReference
							{
								Type = ReferenceType.SecurityScheme,
								Id = "oauth2",
							}
						},
						Array.Empty<string>()
						}
					});`
