### ISSUE TITLE
Confusing Documentation for Strongly Typed Hubs & Invalid Schema Generation

### ISSUE THREAD

**Issue by dapperdandev** [Dorin-Mocan/SignalRSwaggerGen#42]
Thanks for the tool. I'm looking forward to getting it working. I'm having a couple of problems.

## Documentation
The documentation for strongly typed hubs is confusing. 

```csharp
[SignalRHub]
public interface ISomeStronglyTypedHub
{
    Task SomeMethod(int arg1, object arg2);
}

public class SomeStronglyTypedHub : Hub<ISomeStronglyTypedHub>
{
    public async Task SomeMethod(int arg1, object arg2)
    {
        await Clients.All.SomeMethod(arg1, arg2);
    }
}
```

While it would technically work, it would result in some weird client code:

```javascript
this.connection.on('someMethod',  (...args) => {...}) // Handle `Clients.All.SomeMethod()`
this.connection.invoke('someMethod', 1, {}) // Invoke `SomeMethod()`
``` 

It feels like it suggests that the client method and the server method are one and the same.

Following the Microsoft examples, they should be differentiated somehow to reduce confusion:

```csharp
[SignalRHub]
public interface ISomeStronglyTypedHub
{
    Task ReceiveMessage(int arg1, object arg2);
}

public class SomeStronglyTypedHub : Hub<ISomeStronglyTypedHub>
{
    public async Task SendMessage(int arg1, object arg2)
    {
        await Clients.All.ReceiveMessage(arg1, arg2);
    }
}
```
https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0#strongly-typed-hubs

## Schema Generation
The other problem I have is that the generated schema fails validation and can't be used with tools that require a valid schema. In my case, Azure API Manager. I copy and pasted the example code from the documentation (same as the first code section above) then ran it through `swagger-cli validate`. The result is:

```
swagger-cli validate .\swagger.json
SyntaxError: Swagger schema validation failed.
  #/paths/~1hubs~1SomeStronglyTypedHub~1SomeMethod/post/responses must NOT have fewer than 1 properties

    at validateSchema (C:\Users\DanielBreen\AppData\Roaming\fnm\node-versions\v18.16.0\installation\node_modules\@apidevtools\swagger-cli\node_modules\@apidevtools\swagger-parser\lib\validators\schema.js:55:15)
    at SwaggerParser.validate (C:\Users\DanielBreen\AppData\Roaming\fnm\node-versions\v18.16.0\installation\node_modules\@apidevtools\swagger-cli\node_modules\@apidevtools\swagger-parser\lib\index.js:169:7)
    at async validate (C:\Users\DanielBreen\AppData\Roaming\fnm\node-versions\v18.16.0\installation\node_modules\@apidevtools\swagger-cli\bin\swagger-cli.js:147:5)
```

A bonus fix would be to include the base class' `negotiate` endpoint.

**Comment by Dorin-Mocan** [comment]
@djbreen7 hi! Thanks for helping me improving the documentation. As for the schema issue, I didn't quite get it. So you have created a hub exactly as in the documentation and the generated swagger.json turns out to be invalid?

**Comment by dapperdandev** [comment]
@Dorin-Mocan Sorry. Meant to get back on a branch that I could grab the ouput swagger.json, but yes, creating a hub exactly as in your documentation with the `[SignalRHub]` annotation produces an open api schema with an empty `responses` property for the hub methods which causes it to fail validation. I used this tool to validate: https://apitools.dev/swagger-cli/ and it produces the same error I get from Azure API Manager when I try to deploy it.

**Comment by Dorin-Mocan** [comment]
@djbreen7 but the methods from the documentation really do not have a return type. Why would the responses property be not empty? If you want it to not be empty, you should have a return type except void, Task and ValueTask.

**Comment by dapperdandev** [comment]
@Dorin-Mocan It gets unclear to me how SignalR handles it under the hood. All I know is that both the websocket and http transports respond with status codes and descriptions. Even without a value/response body, I would expect:

```json
{
    ...
    "responses": {
        "200": {
            "description": "OK"
        }
    }
}
```

That said, I don't think it matters in my case since I'm using websockets. API Manager seems to be happy as long as it knows about the negotiate endpoints. We can't decorate the base negotiate method as far as I know, so probably not worth addressing in this repo.

I just used the API Manager endpoint designer to solve my problem. It seems to work fine with minimal configuration.

```json
    "paths": {
        "/<HUB_PATH>/negotiate": {
            "post": {
                "summary": "<HUB_NAME> Negotiate",
                "parameters": [{
                    "name": "negotiateVersion",
                    "in": "query",
                    "schema": {
                        "type": "integer"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "429": {
                        "description": "Too many requests"
                    }
                }
            }
        }
    }
```
