### ISSUE TITLE
Strong naming

### ISSUE THREAD

**Issue by Toemsel** [Dorin-Mocan/SignalRSwaggerGen#43]
Could you please sign the assembly you publish on NuGet? Else projects with `strong naming` enabled aren't able to use your library.

![image](https://github.com/essencebit/SignalRSwaggerGen/assets/6334140/a70d08bc-8844-45e5-8c0a-8bb72a41b24c)

**Comment by Dorin-Mocan** [comment]
@Toemsel hi! Thanks for reaching out. I'll work on this in the following days, so stay tuned, don't loose hope.

**Comment by Toemsel** [comment]
Else I have to clone and ditch the NuGet 😿

**Comment by Dorin-Mocan** [comment]
@Toemsel I released a new version 4.5.0. Please check. Please toss a star for this repo in order to support my work. Thank you!
