### ISSUE TITLE
wrong path shows up for method

### ISSUE THREAD

**Issue by exedor** [Dorin-Mocan/SignalRSwaggerGen#44]
Thank you for your work on this package! I was hoping for a consistent way to make consumers of my service aware of both the REST endpoints and the websockets API and this help a ton!

In my pipeline configuration, I used the following to change the mount point from that which is automatically generated:

`app.MapHub<SimOp>("api/v1/operate");`

Swagger doc root is at api/v1/docs

I see 2 issues with the generated documentation:
1: The path for the method is always shown as "hubs/<method-name>"
2: Each method shows up as a  POST

I get that there may not be anything you can do about the 2nd one because of the way swagger works as it natively does not support anything other than the standard set of http verbs and the OpenAPI standard likely limited support for web sockets in general, let alone signalr, but is there a way to determine and/or configure this so the generated documentation either doesn't have any path at all, in which case I can document it above, or shows the correctly mapped path to the method?

**Comment by Dorin-Mocan** [comment]
@exedor hi, will take a look at this problem in the following days. Sorry for delayed response, very busy lately. Stay tuned.

**Comment by Dorin-Mocan** [comment]
@exedor you have two options for your first issue. One is to set the path for each hub in particular by using the _`path`_ parameter of **`SignalRHub`** attribute. Second is to set the _`HubPathFunc`_ of **`SignalRSwaggerGenOptions`**, that will generate a path for each hub for which the path was not set explicitly, using option one.
