### ISSUE TITLE
Property name is lowercased

### ISSUE THREAD

**Issue by ndc** [Dorin-Mocan/SignalRSwaggerGen#47]
Hello,

Thanks for sharing this library! I'm currently playing with it.
I found that in the generated swagger if the parameter is an object the property names are lowercased. For example this is my interface:

``` cs
using SignalRSwaggerGen.Attributes;

namespace MyProject.Hub
{
    [SignalRHub]
    public interface IChatClient
    {
        Task NotificationFromServer(NotificationFromServerRequest request);
    }

    public class NotificationFromServerRequest
    {
        public string Something { get; set; }
    }
}
```

In the swagger the property `Something` becomes `something`.
Is that something that I can configure?
I have tried changing the NameTransformer to ToCamelTransformer but that only affect the endpoint name, not the parameter names:

``` cs
builder.Services.AddSwaggerGen(o =>
{
    o.AddSignalRSwaggerGen(b =>
    {
        b.AutoDiscover = SignalRSwaggerGen.Enums.AutoDiscover.MethodsAndParams;
        b.NameTransformer = new SignalRSwaggerGen.Naming.ToCamelTransformer();
    });
});
```

For SignalR itself the configuration is in AddJsonProtocol:

``` cs
builder.Services.AddSignalR()
    .AddJsonProtocol(o => o.PayloadSerializerOptions.PropertyNamingPolicy = null);  // to tell SignalR to not change the casings
```

**Comment by Dorin-Mocan** [comment]
@ndc hi! This behavior is not related to my package. This package only extends Swashbuckle's package. Please raise an issue on Swashbuckle's repo and see what they say. Good luck!

**Comment by Dorin-Mocan** [comment]
@ndc hi! This behavior is not related to my package. This package only extends Swashbuckle's package. Please raise an issue on Swashbuckle's repo and see what they say. Good luck!

**Comment by ndc** [comment]
Thank for the info! I googled Swashbuckle issues and found that I should also turn off minimal API's PropertyNamingPolicy too (not just signalR's PropertyNamingPolicy):

``` cs
builder.Services.Configure<JsonOptions>(o =>
{
    o.JsonSerializerOptions.PropertyNamingPolicy = null;
});
```
