### ISSUE TITLE
Negociate method

### ISSUE THREAD

**Issue by diegoferreirax** [Dorin-Mocan/SignalRSwaggerGen#49]
Hello, what's up! 

I have a question for you guys. The "negotiate" method does not appear in swagger. Can we enable it?

exemple: 
http://localhost:PORT/hub-custom-name/negotiate?negotiateVersion=1

This method return some informations about signalR service, is default of signalR. But not appear in swagger.

**Comment by Dorin-Mocan** [comment]
Hi @diegoferreirax . That method that you mentioned has nothing to do with my package. Maybe it's somehow related to Swashbuckle Swagger, and in this case you better ask them :)

**Comment by diegoferreirax** [comment]
Hi @Dorin-Mocan, thank's by your report. 

I found a solution with DocumentFilter. Thank you very much.

`services.AddSwaggerGen(c =>
{
    c.DocumentFilter<CustomDocumentFilter>();
});`
