### ISSUE TITLE
Show Parameters in Swagger

### ISSUE THREAD

**Issue by ArtemiyGazizyanov** [Dorin-Mocan/SignalRSwaggerGen#5]
Hello!

Can I see the parameters of SignalR methods in your Swagger?  Or it's not supported?
![image](https://user-images.githubusercontent.com/69801163/131771192-5e6c43eb-4f88-48f7-8e23-947fc8e0a277.png)

**Comment by ArtemiyGazizyanov** [comment]
Oh!
I figured it out with your comment here: https://stackoverflow.com/questions/28948517/how-do-i-generate-api-documentation-for-signalr/68021371#68021371

I should use [SignalRArg] attribute before parameters.

**Comment by Dorin-Mocan** [comment]
@ArtemiyGazizyanov , hello. You could use AutoDiscover option on SignalRMethod or SignalRHub attributes. Check their parameters. If you enable AutoDiscover, you don't need to add attributes for each method arg.
