### ISSUE TITLE
ChannelReader<string>  as an input

### ISSUE THREAD

**Issue by alimhabib** [Dorin-Mocan/SignalRSwaggerGen#6]
Hi  I have a method with ChannelReader<string>  as input but I want to have something like Request example instead of showing the channel, any idea how to do this please

**Comment by Dorin-Mocan** [comment]
Hello @alimhabib, what do you mean by request example? Please provide more details, so that I can help you asap.

**Comment by alimhabib** [comment]
Hi @Dorin-Mocan  so in swagger we can have  [SwaggerRequestExample(typeof(Result) , typeof(Result) )]  whhich is translated in OpenAPI to Request Example, in my case In the signalR arg I want to show model which is called via Channel not the channel model it self

**Comment by Dorin-Mocan** [comment]
@alimhabib , I'll investigate this possibility and come back to you hopefully by Monday. Hope you're not in a rush.

**Comment by alimhabib** [comment]
@Dorin-Mocan i had time to implement it looking forward to your opinion

**Comment by Dorin-Mocan** [comment]
@alimhabib , the past days I didn't have access to my laptop, so couldn't do anything. I'll take a look today in the evening. Thanks for understanding!

**Comment by alimhabib** [comment]
@Dorin-Mocan  Thanks a lot, I created pull request for it

**Comment by Dorin-Mocan** [comment]
@alimhabib hello. I released the version 2.3.0, which has support for request body. Please check if this is what you needed. Also sorry for delayed implementation.

**Comment by alimhabib** [comment]
@Dorin-Mocan  Thanks a lot, this is what am looking for, happy I inspired you. one more thing I can't find the license for this nugget is it MIT license?

**Comment by Dorin-Mocan** [comment]
@alimhabib yes, it's MIT.

**Comment by Dorin-Mocan** [comment]
I'll add the license next with next features, if any.
